[program:church-calendar-queue]
directory=/var/www/churchWorkingCalendar
command=/usr/bin/php artisan queue:work --sleep=1 --tries=1 --timeout=120
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/church-calendar-queue.log
stopwaitsecs=3600
